address | Provides functionality for storing, validating and displaying international postal addresses | composer require 'drupal/address:^1.12' | ^9.2 || ^10 | https://www.drupal.org/project/address
addtoany | Share buttons for Drupal including AddToAny's universal sharing button, Facebook, Mastodon, Bluesky, Pinterest, WhatsApp, Reddit, SMS, email, and many more | composer require 'drupal/addtoany:^2.0' | ^10 || ^11 | https://www.drupal.org/project/addtoany
admin_toolbar | Improves the default administration toolbar menu by turning it into a drop-down for fast access to all administration pages | composer require 'drupal/admin_toolbar:^3.6' | ^9.5 || ^10 || ^11 | https://www.drupal.org/project/admin_toolbar
advagg | Aggregates CSS and JS files for improved page load performance with advanced aggregation options | composer require 'drupal/advagg:^6.0' | ^10 | https://www.drupal.org/project/advagg
alogin | Adds an extra layer of security with two-factor authentication for user logins | composer require 'drupal/alogin:^2.0' | ^10 || ^11 | https://www.drupal.org/project/alogin
announcement_modal | The Announcement modal module provides an appealing modal window on top of your page | composer require 'drupal/announcement_modal:^207.0' | ^10 || ^11 | https://www.drupal.org/project/announcement_modal
antibot | Prevents spam submissions on forms by checking if JavaScript is enabled and human-like activity occurs | composer require 'drupal/antibot:^2.0' | ^10 || ^11 | https://www.drupal.org/project/antibot
asset_injector | Provides administrators with a quick and easy way of injecting CSS and JavaScript into pages | composer require 'drupal/asset_injector:^2.0' | ^10 || ^11 | https://www.drupal.org/project/asset_injector
auto_entitylabel | Automatically generates labels for content types, taxonomy terms, and other entities | composer require 'drupal/auto_entitylabel:^3.0' | ^10 || ^11 | https://www.drupal.org/project/auto_entitylabel
automatic_updates | Provides Automatic Update of Drupal core and a form to update contrib projects | composer require 'drupal/automatic_updates:^9.0' | ^10 || ^11 | https://www.drupal.org/project/automatic_updates
backup_migrate | Provides an easy-to-use UI for backing up and restoring Drupal databases and files with compression and schedules | composer require 'drupal/backup_migrate:^5.1' | ^9.3 || ^10 | https://www.drupal.org/project/backup_migrate
bg_image_formatter | Provides an image formatter that allows you to set an image in background of a tag | composer require 'drupal/bg_image_formatter:^2.0' | ^10 || ^11 | https://www.drupal.org/project/bg_image_formatter
block_class | Provides a field to add CSS classes to a block from the user interface | composer require 'drupal/block_class:^4.0' | ^10 || ^11 | https://www.drupal.org/project/block_class
block_styles | Allows site builders to select from a list of styles to apply to layout builder blocks and sections | composer require 'drupal/block_styles:^2.0' | ^10 || ^11 | https://www.drupal.org/project/block_styles
bookable_calendar | A very easy to use Bookable Calendar module for scheduling and reservations | composer require 'drupal/bookable_calendar:^2.0' | ^10 || ^11 | https://www.drupal.org/project/bookable_calendar
bootstrap_basic_image_gallery | Provides an image formatter that displays images as a simple Bootstrap-based image gallery | composer require 'drupal/bootstrap_basic_image_gallery:^2.0' | ^10 || ^11 | https://www.drupal.org/project/bootstrap_basic_image_gallery
bootstrap_library | Provides Bootstrap framework assets (CSS and JS) for Drupal themes | composer require 'drupal/bootstrap_library:^2.0' | ^10 || ^11 | https://www.drupal.org/project/bootstrap_library
bricks | A new way of building pages on top of Entity Reference, Display Modes, Layout API, tabledrag.js and Flat Tables | composer require 'drupal/bricks:^8.0' | ^10 || ^11 | https://www.drupal.org/project/bricks
calendar_link | Provides Twig functions for generating links for various calendaring services like Google Calendar, iCal, and Outlook | composer require 'drupal/calendar_link:^3.0' | ^10 || ^11 | https://www.drupal.org/project/calendar_link
ckeditor_iframe | Integrates the CKEditor iFrame Dialog for embedding iframe content in CKEditor | composer require 'drupal/ckeditor_iframe:^2.0' | ^10 || ^11 | https://www.drupal.org/project/ckeditor_iframe
coffee | A keyboard navigation tool to quickly access Drupal admin pages without clicking through menus | composer require 'drupal/coffee:^2.0' | ^10.2 || ^11 | https://www.drupal.org/project/coffee
components | Makes it easier for a theme to organize its components by registering Twig namespaces | composer require 'drupal/components:^3.0' | ^10 || ^11 | https://www.drupal.org/project/components
contact_block | Provides contact forms in a block using the Drupal core Contact module forms | composer require 'drupal/contact_block:^2.0' | ^10 || ^11 | https://www.drupal.org/project/contact_block
content_access | Manages permissions for content types by role and author with custom view, edit and delete permissions | composer require 'drupal/content_access:^2.0' | ^10 || ^11 | https://www.drupal.org/project/content_access
content_browser | Provides a default Entity Browser for browsing and selecting content from a feature-rich grid view | composer require 'drupal/content_browser:^3.0' | ^10 || ^11 | https://www.drupal.org/project/content_browser
crop | Provides basic API for image cropping that other modules can use | composer require 'drupal/crop:^2.0' | ^10 || ^11 | https://www.drupal.org/project/crop
ctools | A developer toolkit that provides APIs and utilities to improve the developer experience | composer require 'drupal/ctools:^4.0' | ^9.5 || ^10 | https://www.drupal.org/project/ctools
devel | Contains helper functions and pages for Drupal developers and inquisitive admins including debug blocks and menu tabs | composer require 'drupal/devel:^5.0' | ^10.3 || ^11 | https://www.drupal.org/project/devel
diff | Provides a visual comparison between two content revisions with customizable display options | composer require 'drupal/diff:^2.0' | ^10 || ^11 | https://www.drupal.org/project/diff
domain | Allows managing multiple domains from a single Drupal installation for multi-site configurations | composer require 'drupal/domain:^2.0' | ^10 || ^11 | https://www.drupal.org/project/domain
dropzonejs | Drupal integration for DropzoneJS - an open source library providing drag'n'drop file uploads with image previews | composer require 'drupal/dropzonejs:^5.0' | ^10 || ^11 | https://www.drupal.org/project/dropzonejs
easy_breadcrumb | Updates the core Breadcrumb block to include the current page title with configurable settings | composer require 'drupal/easy_breadcrumb:^2.0' | ^10 || ^11 | https://www.drupal.org/project/easy_breadcrumb
eca | ECA is the no-code solution that empowers you to orchestrate your Drupal site with a powerful rules engine | composer require 'drupal/eca:^1.0' | ^10 || ^11 | https://www.drupal.org/project/eca
editor_advanced_link | Enhances the CKEditor link dialog by allowing title, class, id, target, rel and other attributes | composer require 'drupal/editor_advanced_link:^2.0' | ^10 || ^11 | https://www.drupal.org/project/editor_advanced_link
entity_browser | Provides a flexible and generic entity browsing and selecting tool using views and other browsers | composer require 'drupal/entity_browser:^2.10' | ^9.5 || ^10 | https://www.drupal.org/project/entity_browser
environment_indicator | Adds a configurable color bar to indicate what server environment you're working in | composer require 'drupal/environment_indicator:^4.0' | ^10 || ^11 | https://www.drupal.org/project/environment_indicator
eu_cookie_compliance | Provides a GDPR cookie banner for gathering user consent when storing cookies | composer require 'drupal/eu_cookie_compliance:^2.0' | ^10 || ^11 | https://www.drupal.org/project/eu_cookie_compliance
extlink | Finds all external links on a web page and adds an external or mail icon to indicate off-site links | composer require 'drupal/extlink:^2.0' | ^10 || ^11 | https://www.drupal.org/project/extlink
fac | The Fast Autocomplete module provides fast IMDB-like suggestions below a text input field | composer require 'drupal/fac:^2.0' | ^10 || ^11 | https://www.drupal.org/project/fac
facets | Allows users to add additional filters (facets) to search results to further refine results | composer require 'drupal/facets:^3.0' | ^10 || ^11 | https://www.drupal.org/project/facets
fakeobjects | Plugin to create representative images for certain elements in editable content | composer require 'drupal/fakeobjects:^4.0' | ^10 || ^11 | https://www.drupal.org/project/fakeobjects
fast_404 | Provides fast 404 pages to improve performance and user experience for missing pages | composer require 'drupal/fast_404:^2.0' | ^10 || ^11 | https://www.drupal.org/project/fast_404
field_formatter_class | Provides a field formatter to add CSS classes to entity field display | composer require 'drupal/field_formatter_class:^2.0' | ^10 || ^11 | https://www.drupal.org/project/field_formatter_class
flexslider | Integrates the Flex Slider library with Drupal for building responsive, resizable slideshows | composer require 'drupal/flexslider:^3.0' | ^10 || ^11 | https://www.drupal.org/project/flexslider
focal_point | Allows you to specify the portion of an image that is most important for cropping | composer require 'drupal/focal_point:^2.0' | ^10 || ^11 | https://www.drupal.org/project/focal_point
fontawesome | Provides a plugin to use Font Awesome icons directly from CKEditor with icon fields for entities | composer require 'drupal/fontawesome:^2.0' | ^9.2 || ^10 | https://www.drupal.org/project/fontawesome
fontawesome_iconpicker | Enhances Core Text Fields to use Fontawesome Iconpicker to select icons | composer require 'drupal/fontawesome_iconpicker:^3.0' | ^10 || ^11 | https://www.drupal.org/project/fontawesome_iconpicker
fontawesome_menu_icons | Adds Font Awesome icons to menu items in Drupal | composer require 'drupal/fontawesome_menu_icons:^3.0' | ^10 || ^11 | https://www.drupal.org/project/fontawesome_menu_icons
geo_location | Provides a field type to store and display geographical locations | composer require 'drupal/geo_location:^1.0' | ^10 || ^11 | https://www.drupal.org/project/geo_location
geolocation | Provides a field type to store geographical locations as latitude/longitude with display integration | composer require 'drupal/geolocation:^4.0' | ^10 || ^11 | https://www.drupal.org/project/geolocation
gin | A completely redesigned UI layout with Darkmode and fresh look for Drupal Admin interface | composer require 'drupal/gin:^3.0' | ^10 || ^11 | https://www.drupal.org/project/gin
gin_toolbar | Helper module to bring the Gin Toolbar into the Frontend of your site | composer require 'drupal/gin_toolbar:^2.1' | ^10 || ^11 | https://www.drupal.org/project/gin_toolbar
google_tag | Integrates Google Tag Manager with Drupal for tracking and analytics | composer require 'drupal/google_tag:^2.0' | ^10 || ^11 | https://www.drupal.org/project/google_tag
gridstack | Provides integration with gridstack.js as a dynamic layout creator for two-dimensional layouts | composer require 'drupal/gridstack:^1.0' | ^10 || ^11 | https://www.drupal.org/project/gridstack
honeypot | Uses honeypot and timestamp strategies to deter spam bots from completing forms | composer require 'drupal/honeypot:^2.2' | ^10.3 || ^11 | https://www.drupal.org/project/honeypot
hreflang | Automatically adds hreflang tags to pages for each enabled language | composer require 'drupal/hreflang:^2.0' | ^10 || ^11 | https://www.drupal.org/project/hreflang
image_effects | Adds various visual effects and filters to images for enhanced image manipulation | composer require 'drupal/image_effects:^5.0' | ^10 || ^11 | https://www.drupal.org/project/image_effects
image_styles_generator | Warms up image styles for faster loading and CI/CD environments | composer require 'drupal/image_styles_generator:^1.0' | ^10 || ^11 | https://www.drupal.org/project/image_styles_generator
image_url_formatter | Adds a URL formatter for image fields to output image URL directly | composer require 'drupal/image_url_formatter:^2.0' | ^10 || ^11 | https://www.drupal.org/project/image_url_formatter
imce | A file manager featuring personal directories and quotas for managing files | composer require 'drupal/imce:^3.1' | ^9.3 || ^10 || ^11 | https://www.drupal.org/project/imce
inline_entity_form | Provides a widget for creating and editing entities inline within parent forms | composer require 'drupal/inline_entity_form:^3.0@RC' | ^8.8 || ^9 || ^10 || ^11 | https://www.drupal.org/project/inline_entity_form
jsonapi_boost | Improves the performance of the JSON:API module by cache warming resource types | composer require 'drupal/jsonapi_boost:^2.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_boost
jsonapi_extras | Customizes the JSON:API module with configuration options for your API | composer require 'drupal/jsonapi_extras:^3.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_extras
jsonapi_include | Makes it easy to parse entity references with JSON:API | composer require 'drupal/jsonapi_include:^2.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_include
jsonapi_node_preview_tab | Adds a tab to nodes for quick preview of node's JSON:API representation | composer require 'drupal/jsonapi_node_preview_tab:^1.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_node_preview_tab
jsonapi_schema | Provides JSON-Schema formatted schemas for JSON:API resources | composer require 'drupal/jsonapi_schema:^1.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_schema
jsonapi_views | Creates JSON:API Resource for each Views display for external data consumption | composer require 'drupal/jsonapi_views:^9.0' | ^10 || ^11 | https://www.drupal.org/project/jsonapi_views
juicebox | Provides integration between the Juicebox HTML5 responsive gallery library and Drupal | composer require 'drupal/juicebox:^2011.0' | ^10 || ^11 | https://www.drupal.org/project/juicebox
layout_builder_styles | Allows site builders to select from a list of styles to apply to layout builder blocks | composer require 'drupal/layout_builder_styles:^2.0' | ^10 || ^11 | https://www.drupal.org/project/layout_builder_styles
layout_library | Provides a layout library allowing content editors to pick from pre-defined layouts | composer require 'drupal/layout_library:^2.0' | ^10 || ^11 | https://www.drupal.org/project/layout_library
leaflet | Drupal advanced integration with the Leaflet JS mapping library for interactive maps | composer require 'drupal/leaflet:^10.0' | ^10 || ^11 | https://www.drupal.org/project/leaflet
link_attributes | Provides an additional widget for the link field allowing users to set attributes | composer require 'drupal/link_attributes:^2.0' | ^10 || ^11 | https://www.drupal.org/project/link_attributes
link_icons | Field formatter for Link fields to display icons for the linked service | composer require 'drupal/link_icons:^3.0' | ^10 || ^11 | https://www.drupal.org/project/link_icons
linkit | Provides autocomplete functionality for Drupal link interfaces supporting nodes, users, taxonomy, files | composer require 'drupal/linkit:^6.0' | ^10 || ^11 | https://www.drupal.org/project/linkit
media_bulk_upload | Drupal module to bulk upload files and create media entities automatically using DropzoneJS | composer require 'drupal/media_bulk_upload:^3.0' | ^10 || ^11 | https://www.drupal.org/project/media_bulk_upload
media_directories | Alternative way to browse and pick Media with a jsTree-based directory structure | composer require 'drupal/media_directories:^2.0' | ^10 || ^11 | https://www.drupal.org/project/media_directories
media_entity_download | Prevents links from breaking when updating or uploading new files for media entities | composer require 'drupal/media_entity_download:^3.0' | ^10 || ^11 | https://www.drupal.org/project/media_entity_download
media_file_delete | Gives content editors option to delete the associated file when deleting a media entity | composer require 'drupal/media_file_delete:^206.0' | ^10 || ^11 | https://www.drupal.org/project/media_file_delete
menu_block | Enhances Drupal core menus with functionality to expand all menu links with children | composer require 'drupal/menu_block:^3.0' | ^10 || ^11 | https://www.drupal.org/project/menu_block
metatag | Allows generating meta tags for site content including OpenGraph, Twitter Cards, and more | composer require 'drupal/metatag:^2.2' | ^10.3 || ^11 | https://www.drupal.org/project/metatag
mobile_detect | Lightweight mobile detection module based on Mobile_Detect.php library | composer require 'drupal/mobile_detect:^3.0' | ^10 || ^11 | https://www.drupal.org/project/mobile_detect
monitoring | Vendor independent framework for deeply monitoring Drupal and all its projects | composer require 'drupal/monitoring:^5.0' | ^10 || ^11 | https://www.drupal.org/project/monitoring
oauth_login_oauth2 | Provides OAuth2 login functionality for Drupal | composer require 'drupal/oauth_login_oauth2:^2.0' | ^10 || ^11 | https://www.drupal.org/project/oauth_login_oauth2
openai | AI module framework for integrating OpenAI and other AI services with Drupal | composer require 'drupal/openai:^203.0' | ^10 || ^11 | https://www.drupal.org/project/openai
pathauto | Automatically generates URL/path aliases for content without requiring manual specification | composer require 'drupal/pathauto:^1.13' | ^9.4 || ^10 || ^11 | https://www.drupal.org/project/pathauto
photoswipe | Displays picture galleries using PhotoSwipe JavaScript lightbox library with mobile browsing features | composer require 'drupal/photoswipe:^5.0' | ^10 || ^11 | https://www.drupal.org/project/photoswipe
project_browser | Allows site builders to easily find and install modules from within Drupal admin | composer require 'drupal/project_browser:^2.0' | ^10 || ^11 | https://www.drupal.org/project/project_browser
pwa | Progressive Web Apps providing native-like experience with offline capability and homescreen installation | composer require 'drupal/pwa:^2.0' | ^10 || ^11 | https://www.drupal.org/project/pwa
quick_node_clone | Enables cloning of nodes by adding a Clone tab that creates a new node with populated fields | composer require 'drupal/quick_node_clone:^2.0' | ^10 || ^11 | https://www.drupal.org/project/quick_node_clone
rabbit_hole | Controls display of content on its own page by blocking access to content | composer require 'drupal/rabbit_hole:^2.0' | ^10 || ^11 | https://www.drupal.org/project/rabbit_hole
radix | Component-based theme for Drupal with Bootstrap 5, Sass, ES6, BrowserSync built-in | composer require 'drupal/radix:^6.0' | ^10 || ^11 | https://www.drupal.org/project/radix
radix_layouts | Responsive panels layouts for Radix theme | composer require 'drupal/radix_layouts:^2.0' | ^10 || ^11 | https://www.drupal.org/project/radix_layouts
recaptcha | Uses the reCAPTCHA web service to improve the CAPTCHA system | composer require 'drupal/recaptcha:^3.3' | ^10 || ^11 | https://www.drupal.org/project/recaptcha
redirect | Creates manual redirects and maintains canonical URLs for all content | composer require 'drupal/redirect:^1.11' | ^9.2 || ^10 || ^11 | https://www.drupal.org/project/redirect
redirect_after_login | Redirects users to a specified page after login | composer require 'drupal/redirect_after_login:^2.0' | ^10 || ^11 | https://www.drupal.org/project/redirect_after_login
redis | Integration of Drupal with Redis key-value store providing cache, lock, flood and queue backends | composer require 'drupal/redis:^2.0' | ^10 || ^11 | https://www.drupal.org/project/redis
restrict_ip | Allows administrators to restrict access to the site to defined IP addresses | composer require 'drupal/restrict_ip:^127.0' | ^10 || ^11 | https://www.drupal.org/project/restrict_ip
robotstxt | Manages robots.txt file for Drupal multisite installations | composer require 'drupal/robotstxt:^1.0' | ^10 || ^11 | https://www.drupal.org/project/robotstxt
sam | Lullabot-sponsored module for advanced site administration | composer require 'drupal/sam:^1.0' | ^10 || ^11 | https://www.drupal.org/project/sam
scheduler | Gives editors ability to schedule content, media, and products for publishing at specified dates | composer require 'drupal/scheduler:^2.0' | ^8 || ^9 || ^10 || ^11 | https://www.drupal.org/project/scheduler
schema_metatag | Extends Metatag module to display structured data as JSON LD | composer require 'drupal/schema_metatag:^3.0' | ^10 || ^11 | https://www.drupal.org/project/schema_metatag
search404 | Handles 404 pages with search functionality | composer require 'drupal/search404:^2.0' | ^10 || ^11 | https://www.drupal.org/project/search404
seckit | Provides Drupal with various security-hardening options to mitigate web application vulnerabilities | composer require 'drupal/seckit:^2.0' | ^10 || ^11 | https://www.drupal.org/project/seckit
security_review | Automates testing for easy-to-make mistakes that render your site insecure | composer require 'drupal/security_review:^3.0' | ^10 || ^11 | https://www.drupal.org/project/security_review
semanticviews | Makes unformatted views styles more readily configurable without template overrides | composer require 'drupal/semanticviews:^3.0' | ^10 || ^11 | https://www.drupal.org/project/semanticviews
seo_checklist | Uses best practices to check your website for proper search engine optimization | composer require 'drupal/seo_checklist:^2012.0' | ^10 || ^11 | https://www.drupal.org/project/seo_checklist
simple_gmap | Simplest way to get a Google Map displayed with your content | composer require 'drupal/simple_gmap:^4.0' | ^10 || ^11 | https://www.drupal.org/project/simple_gmap
simple_sitemap | Generates standard-compliant hreflang XML sitemaps for SEO with IndexNow support | composer require 'drupal/simple_sitemap:^4.1' | ^10 || ^11 | https://www.drupal.org/project/simple_sitemap
site_audit | Drupal static site analysis platform generating reports with actionable recommendations | composer require 'drupal/site_audit:^203.0' | ^10 || ^11 | https://www.drupal.org/project/site_audit
sitemap | Provides a way for visitors to navigate your website using an overview of notable pages | composer require 'drupal/sitemap:^2.0' | ^10 || ^11 | https://www.drupal.org/project/sitemap
sitewide_alert | Adds ability to show alerts at the top of your site | composer require 'drupal/sitewide_alert:^3.0' | ^10 || ^11 | https://www.drupal.org/project/sitewide_alert
smart_date | Provides a more user-friendly date field with duration concept and easy admin UI | composer require 'drupal/smart_date:^207.0' | ^10 || ^11 | https://www.drupal.org/project/smart_date
smart_trim | Enables smart trimmed option controlling trim length, measurement, suffix and more link | composer require 'drupal/smart_trim:^2.0' | ^10 || ^11 | https://www.drupal.org/project/smart_trim
social_login | Allows users to register and login with existing social network accounts | composer require 'drupal/social_login:^3.0' | ^10 || ^11 | https://www.drupal.org/project/social_login
social_media_links | Provides a configurable block displaying links to social media profiles | composer require 'drupal/social_media_links:^3.0' | ^10 || ^11 | https://www.drupal.org/project/social_media_links
styleguide | Provides a visual testing page for Drupal themes to compare display of common elements | composer require 'drupal/styleguide:^2.0' | ^10 || ^11 | https://www.drupal.org/project/styleguide
taxonomy_formatter | Provides a custom formatter for taxonomy items with better HTML output | composer require 'drupal/taxonomy_formatter:^2.0' | ^10 || ^11 | https://www.drupal.org/project/taxonomy_formatter
terms_of_use | Adds Terms of Use and agreement checkbox to the registration page | composer require 'drupal/terms_of_use:^1.0' | ^10 || ^11 | https://www.drupal.org/project/terms_of_use
tinypng | Provides TinyPNG integration for lossy PNG compression | composer require 'drupal/tinypng:^1.0' | ^10 || ^11 | https://www.drupal.org/project/tinypng
token | Provides placeholder variables (tokens) and interface for browsing available tokens | composer require 'drupal/token:^1.14' | ^9.2 || ^10 | https://www.drupal.org/project/token
token_filter | Lets you use special placeholders (tokens) as filters in text fields | composer require 'drupal/token_filter:^2.0' | ^10 || ^11 | https://www.drupal.org/project/token_filter
twitter_block | Lightweight module to create blocks which display embedded Twitter timelines | composer require 'drupal/twitter_block:^4.0' | ^10 || ^11 | https://www.drupal.org/project/twitter_block
type_tray | Lullabot-sponsored project for enhanced content type management | composer require 'drupal/type_tray:^1.0' | ^10 || ^11 | https://www.drupal.org/project/type_tray
uli_custom_workflow | Custom workflow for unique login-links (ULI) in Drupal | composer require 'drupal/uli_custom_workflow:^2.0' | ^10 || ^11 | https://www.drupal.org/project/uli_custom_workflow
ultimate_cron | Ultimate Cron handling for Drupal running jobs individually in parallel | composer require 'drupal/ultimate_cron:^207.0' | ^10 || ^11 | https://www.drupal.org/project/ultimate_cron
upgrade_status | Reviews Drupal major upgrade readiness of the environment and components | composer require 'drupal/upgrade_status:^4.0' | ^10 || ^11 | https://www.drupal.org/project/upgrade_status
url_embed | Allows URLs to be embedded within text areas using WYSIWYG editor | composer require 'drupal/url_embed:^3.0' | ^10 || ^11 | https://www.drupal.org/project/url_embed
video_embed_facebook | Integration for Facebook videos into Video Embed Field | composer require 'drupal/video_embed_facebook:^3.0' | ^10 || ^11 | https://www.drupal.org/project/video_embed_facebook
video_embed_field | Creates a simple field type to embed videos from YouTube and Vimeo with thumbnails | composer require 'drupal/video_embed_field:^3.0' | ^10 || ^11 | https://www.drupal.org/project/video_embed_field
views_bootstrap | Creates Bootstrap components within Views configuration settings | composer require 'drupal/views_bootstrap:^5.5' | ^10 || ^11 | https://www.drupal.org/project/views_bootstrap
views_bulk_edit | Allows bulk updating of entity values via views bulk actions | composer require 'drupal/views_bulk_edit:^201.0' | ^10 || ^11 | https://www.drupal.org/project/views_bulk_edit
views_field_view | Embeds a list inside each row of another view | composer require 'drupal/views_field_view:^3.0' | ^10 || ^11 | https://www.drupal.org/project/views_field_view
views_ical | Creates iCal feeds with Views using Fields row style | composer require 'drupal/views_ical:^4.0' | ^10 || ^11 | https://www.drupal.org/project/views_ical
views_infinite_scroll | Loads and displays pages of any view inline using AJAX | composer require 'drupal/views_infinite_scroll:^2.0' | ^10 || ^11 | https://www.drupal.org/project/views_infinite_scroll
views_json_source | Extension of views module to work with external JSON data through views | composer require 'drupal/views_json_source:^2.0' | ^10 || ^11 | https://www.drupal.org/project/views_json_source
views_timelinejs | Renders result rows as TimelineJS slides and eras | composer require 'drupal/views_timelinejs:^4.0' | ^10 || ^11 | https://www.drupal.org/project/views_timelinejs
webform | Build forms to collect data from site visitors with conditional logic and email notifications | composer require 'drupal/webform:^6.2' | ^10.2 || ^11 | https://www.drupal.org/project/webform
webp | Creates a WebP copy of image style derivatives to decrease loading times | composer require 'drupal/webp:^1.0' | ^10 || ^11 | https://www.drupal.org/project/webp
weight | Provides a weight field that can be added to any fieldable entity for customized sorting | composer require 'drupal/weight:^3.0' | ^10 || ^11 | https://www.drupal.org/project/weight
yoast_seo | Improves Drupal SEO by helping optimize content around keywords | composer require 'drupal/yoast_seo:^2.0' | ^10 || ^11 | https://www.drupal.org/project/yoast_seo
